- name: setup catalogue server
  hosts: catalogue
  become: yes
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present
    
    - name: Add the user roboshop
      ansible.builtin.user:
        name: roboshop
        comment: system user roboshop
        system: true
        shell: /sbin/nologin
        home: /app

    - name: Remove app directory
      ansible.builtin.file:
        path: /app
        state: absent    

    - name: Create app directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: delete catalogue file
      ansible.builtin.file:
        path: /tmp/catalogue.zip
        state: absent

    - name: Download foo.conf
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Extract catalogue.zip
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install dependencies
      community.general.npm:
        path: /app

    - name: copy catalogue service
      ansible.builtin.copy: 
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: copy mongo.repo
      ansible.builtin.copy: 
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
    
    - name: install mongodb client
      ansible.builtin.package:
        name: mongodb-mongosh
        state: present

    - name: connnect to mongodb catalogue
      ansible.builtin.command: mongosh mongodb.daws86s.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
      register: catalogue_output    

    - name: load master data
      ansible.builtin.shell: mongosh --host mongodb.daws86s.icu </app/db/master-data.js
      when: catalogue_output.stdout | int < 0

    - name: daemon reload enable and start
      ansible.builtin.systemd_service:
        name: catalogue
        enabled: true
        state: started
        daemon_reload: true
