- name: setup rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy rabbitmq repo
    ansible.builtin.copy:
     src: rabbitmq.repo
     dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install  rabbitmq server
    ansible.builtin.package:
      name:  rabbitmq-server
      state: present

  - name: start and enable mysql
    ansible.builtin.service:
      name:  rabbitmq
      state: started
      enabled: yes

  - name: Add user to server and assign full access control
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
      
    

    