- name: setup user server
  hosts: user
  become: yes
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present
    
    - name: Add the user roboshop
      ansible.builtin.user:
        name: roboshop
        comment: system user roboshop
        system: true
        shell: /sbin/nologin
        home: /app

    - name: Remove app directory
      ansible.builtin.file:
        path: /app
        state: absent    

    - name: Create app directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: delete user file
      ansible.builtin.file:
        path: /tmp/user.zip
        state: absent

    - name: Download foo.conf
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip

    - name: Extract user.zip
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes

    - name: Install dependencies
      community.general.npm:
        path: /app

    - name: copy user service
      ansible.builtin.copy: 
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: daemon reload enable and start
      ansible.builtin.systemd_service:
        name: user
        enabled: true
        state: started
        daemon_reload: true
    